---
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8

  - repo: https://github.com/PyCQA/pylint
    rev: v2.14.5
    hooks:
      - id: pylint
        args: ['--disable=missing-function-docstring', '--disable=missing-module-docstring', '--disable=import-error', '--disable=too-many-return-statements']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
